version: "3.5"

services:
   api01:
    image: kleytonsolinho/rinha-de-backend-2024-q1:latest
    container_name: api01
    platform: linux/amd64
    ports:
      - 8081:8080
    environment:
      - DB_HOSTNAME=db
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"
   db:
    image: mysql:5.7
    container_name: rinha-de-backend-2024-q1-mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rinha-de-backend-mysql
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
