version: "3.5"

services:
   api01: &api
    image: kleytonsolinho/rinha-de-backend-2024-q1:latest
    container_name: api01
    hostname: api01
    platform: linux/amd64
    ports:
      - 8081:8080
    environment:
      - DB_HOSTNAME=db
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

   api02:
    <<: *api 
    container_name: api02
    hostname: api02
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8082:8080"

   nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"
   db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rinha-de-backend-mysql
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1